### PR TITLE
Export data

### PR DESCRIPTION
**Pull request by TheBB**

### CODE REVIEW

**Comment by TheBB** [comment]
This is ready to use now I think. Output in images (choice of color map), G2 or STL.

**Comment by VikingScientist** [comment]
Having linear spline (g2) representation is probably the right decision as the default behaviour. However I would like to draw your attention to [splipy.utils.image.image_height](https://github.com/sintefmath/Splipy/blob/f7bf4ef8e2a15433ec9ac16498b2275cc44e265f/splipy/utils/image.py#L191) which gives a high-order approximation of these kind of datasets.

**Comment by VikingScientist** [comment]
Would also like a screenshot if you have one to spare since I don't have the option of running it on my windows computer right now.

**Comment by TheBB** [comment]
Looks something like this.

file:///home/eivind/Pictures/Screenshot%20from%202020-02-06%2015-11-22.png

**Comment by TheBB** [comment]
Screenshot from 2020-02-06 15-11-22

Okay that's better.

- File: self-explanatory
- Format: PNG, JPEG, G2 or STL - changes automatically when you change the filename, however the filename doesn't change if you change the format... maybe it should (I've annoyed myself a few times already with that)
- Coordinates: lat/lon or UTM33N
- Resolution: right now it says meters but if your coordinates are lat/lon it'll be interpreted as degrees... should change that
- Color map: should be disabled if an image format is selected (to do)
- Zero at sea level: if unchecked, the zero point will be the lowest point in the image, instead of true zero

For G2 and STL, the true geometry is generated. For image formats, we fit the input polygon in the relevant coordinate system to a rectangle, either the minimal bounding rectangle or the maximal interior rectangle. There's some scipy logic for finding these. Rotation can be either fixed (to the target coordinate system), aligned with true north (in UTM33N in Trondheim this is about 4.1 degrees east of the positive y-axis), or freely rotated (in which case we'll compute the optimal rotation to get the best fit). The overshoot or shortfall in the area is displayed, along with the rotation. These computations are not extremely fast, but generally okay unless you pick maximal interior rectangle + free rotation, in which case you'll see the UI noticeably lagging.

I've found that a default setting of maximal interior rectangle + north-aligned rotation works pretty well.

**Pull request merged**
