### PR TITLE
Use qtdesigner to refactor GUI code

### PR DESCRIPTION
**Pull request by TheBB**

### CODE REVIEW

**Comment by VikingScientist** [comment]
I'm guessing dependencies are missing from setup.py

```
Traceback (most recent call last):
  File "/home/kjetijo/.local/bin/geomaker", line 11, in <module>
    load_entry_point('GeoMaker==0.1', 'console_scripts', 'geomaker')()
  File "/home/kjetijo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/kjetijo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/kjetijo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/__main__.py", line 19, in <module>
    from .ui.utils import key_to_text, angle_to_degrees
ModuleNotFoundError: No module named 'geomaker.ui'
```

**Comment by TheBB** [comment]
Had to update setup.py again. Apparently it didn't find nested packages. Try now?

**Comment by VikingScientist** [comment]
Compiling and running.

**Comment by VikingScientist** [comment]
Assertion error encountered. Don't know if its related to this PR 

```
Traceback (most recent call last):
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/__main__.py", line 155, in eventFilter
    self.ui.update_jobs()
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/__main__.py", line 445, in update_jobs
    'Refreshing jobs', cont=self.download_jobs,
  File "/home/kjetijo/.local/lib/python3.6/site-packages/GeoMaker-0.1-py3.6.egg/geomaker/__main__.py", line 384, in run_thread
    assert not self._thread
AssertionError
```

**Comment by VikingScientist** [comment]
Also: what does "download dedicated file" mean?

**Comment by TheBB** [comment]
It's the same as the choice you had earlier, download tiled data or a single dedicated file.

For the assertion error, maybe you hit F5 again before the previous update finished. I guess that can be made clearer.

Have a few other things to fix too before I can merge this.

**Comment by VikingScientist** [comment]
New regions are missing the download button (lower right corner). If the region already was present and  had files associated with it, then no problems.

GeoMaker_005

GeoMaker_006

**Comment by TheBB** [comment]
Yep, that's what I noticed. It should be there now.

**Comment by VikingScientist** [comment]
**Design request:** The download button is kind of a big deal. It's what this entire application is built upon to support. Make it more visible. Make it giant and make it green and make it spell out its entire function.

The "Comment" button to the lower right of this very comment box I'm typing in now here on github is a good thing to take inspiration from.

**Comment by TheBB** [comment]
Fair enough. Better? This lets me remove my ugly hack also.

**Comment by VikingScientist** [comment]
Better. Though it could be *even bigger*. Make it twice as tall. I want a **huge** button.

Also: no there is no error message anymore when the area > 16km<sup>2</sup>

**Comment by TheBB** [comment]
Fixed and updated.

Ah my precious screen real estate.

**Pull request merged**
